[package]
name = "dummy_xml"
version = "0.1.2"
authors = ["vietanhto"]
description = "Fast Non-validating XML DOM parser"
readme = "README.md"
license = "MIT"

[dependencies]

[profile.dev]
opt-level = 0
debug = true
